#ifndef COMMON_LOG_H_
#define COMMON_LOG_H_
#include "ff/log.h"

DEF_LOG_MODULE(main)
DEF_LOG_MODULE(thread)
DEF_LOG_MODULE(para)
DEF_LOG_MODULE(rt)

ENABLE_LOG_MODULE(main)
ENABLE_LOG_MODULE(thread)
ENABLE_LOG_MODULE(para)
ENABLE_LOG_MODULE(rt)

#endif
